project:
  type: website

website:
  title: ""
  description: "This site has now been moved."
  site-url: "https://www.midlandsdecisionsupport.nhs.uk/"
  search: false
  navbar:
    toggle-position: right
    title: false
    collapse-below: lg
    right:
      - icon: github
        href: "https://github.com/The-Strategy-Unit/mdsn-website"
        aria-label: GitHub
      - href: "https://www.strategyunitwm.nhs.uk/publications/midlands-analyst-network-and-huddles"
        text: MDSN Publications
        aria-label: Publications
      - href: "https://www.strategyunitwm.nhs.uk/publications/midlands-analyst-network-and-huddles"
        text: Midlands Analyst Network
        aria-label: Huddles
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



